### ISSUE TITLE
Exit status 1 on npm run build

### ISSUE THREAD

**Issue by tsidel** [mediacurrent/theme_generator_8#127]
I followed the instructions in this video https://www.youtube.com/watch?v=cVyA2v-UwSQ. Even using the older npm `nvm install 14.16.1 && node -v > .nvmrc` command as was shown in the video.

And everything was going fine until I got to npm run build.

Here is the error that displayed in terminal, and I'll paste the npm log as well.

```
[15:35:23] Starting 'concatJS'...
[15:35:23] Finished 'concatJS' after 14 ms
[15:35:23] Finished 'concatCSS' after 24 ms
[15:35:23] Starting 'buildPatternlab'...
Could not find pattern referenced with partial syntax @training_theme/accordion/_accordion-item.twig.
      This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.
Could not find pattern referenced with partial syntax @training_theme/carousel/_carousel-item.twig.
      This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.
-Users/_head "Pattern", "Group" and "Subgroup" hiding by underscore prefix (_*) will be deprecated in the future.
 See https://patternlab.io/docs/hiding-patterns-in-the-navigation/
-Users/_foot "Pattern", "Group" and "Subgroup" hiding by underscore prefix (_*) will be deprecated in the future.
 See https://patternlab.io/docs/hiding-patterns-in-the-navigation/
Error trying to render "components/accordion/accordion.twig". Template "@training_theme/accordion/_accordion-item.twig" is not defined in "components/accordion/accordion.twig" at line 16.
[15:35:24] The following tasks did not complete: default, buildPatternlab
[15:35:24] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! training_theme@1.0.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the training_theme@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeana/.npm/_logs/2021-10-26T20_35_24_342Z-debug.log
```

And here's the npm debug log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jeana/.nvm/versions/node/v14.16.1/bin/node',
1 verbose cli   '/Users/jeana/.nvm/versions/node/v14.16.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle training_theme@1.0.0~prebuild: training_theme@1.0.0
6 info lifecycle training_theme@1.0.0~build: training_theme@1.0.0
7 verbose lifecycle training_theme@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle training_theme@1.0.0~build: PATH: /Users/jeana/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jeana/htdocs/vh-training/web/themes/custom/training_theme/node_modules/.bin:/Users/jeana/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle training_theme@1.0.0~build: CWD: /Users/jeana/htdocs/vh-training/web/themes/custom/training_theme
10 silly lifecycle training_theme@1.0.0~build: Args: [ '-c', 'gulp' ]
11 silly lifecycle training_theme@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle training_theme@1.0.0~build: Failed to exec build script
13 verbose stack Error: training_theme@1.0.0 build: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jeana/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jeana/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid training_theme@1.0.0
15 verbose cwd /Users/jeana/htdocs/vh-training/web/themes/custom/training_theme
16 verbose Darwin 20.6.0
17 verbose argv "/Users/jeana/.nvm/versions/node/v14.16.1/bin/node" "/Users/jeana/.nvm/versions/node/v14.16.1/bin/npm" "run" "build"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error training_theme@1.0.0 build: `gulp`
22 error Exit status 1
23 error Failed at the training_theme@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by tsidel** [comment]
After seeing last week's update to the Read me. I went through the instructions again, and I now get no errors. Closing this issue.
