### ISSUE TITLE
training_theme@1.0.0 build script fails

### ISSUE THREAD

**Issue by tsidel** [mediacurrent/theme_generator_8#128]
I followed the updated readme instructions, and got further in the build. However, now I have these error messages:
```
[truncated.... everything else before here built just fine]
[09:35:21] Starting 'concatJS'...
[09:35:21] Finished 'concatJS' after 15 ms
[09:35:21] Finished 'concatCSS' after 26 ms
[09:35:21] Starting 'buildPatternlab'...
Could not find pattern referenced with partial syntax @training_theme/accordion/_accordion-item.twig.
      This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.
Could not find pattern referenced with partial syntax @training_theme/carousel/_carousel-item.twig.
      This can occur when a pattern was renamed, moved, or no longer exists but it still referenced within a different template or within data as a link.
-Users/_head "Pattern", "Group" and "Subgroup" hiding by underscore prefix (_*) will be deprecated in the future.
 See https://patternlab.io/docs/hiding-patterns-in-the-navigation/
-Users/_foot "Pattern", "Group" and "Subgroup" hiding by underscore prefix (_*) will be deprecated in the future.
 See https://patternlab.io/docs/hiding-patterns-in-the-navigation/
Error trying to render "components/accordion/accordion.twig". Template "@training_theme/accordion/_accordion-item.twig" is not defined in "components/accordion/accordion.twig" at line 16.
[09:35:21] The following tasks did not complete: default, buildPatternlab
[09:35:21] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! training_theme@1.0.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the training_theme@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeana/.npm/_logs/2021-11-01T14_35_21_811Z-debug.log
```

here is the debug log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jeana/.nvm/versions/node/v14.18.1/bin/node',
1 verbose cli   '/Users/jeana/.nvm/versions/node/v14.18.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle training_theme@1.0.0~prebuild: training_theme@1.0.0
6 info lifecycle training_theme@1.0.0~build: training_theme@1.0.0
7 verbose lifecycle training_theme@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle training_theme@1.0.0~build: PATH: /Users/jeana/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jeana/htdocs/vh-training/web/themes/custom/training_theme/node_modules/.bin:/Users/jeana/.nvm/versions/node/v14.18.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle training_theme@1.0.0~build: CWD: /Users/jeana/htdocs/vh-training/web/themes/custom/training_theme
10 silly lifecycle training_theme@1.0.0~build: Args: [ '-c', 'gulp' ]
11 silly lifecycle training_theme@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle training_theme@1.0.0~build: Failed to exec build script
13 verbose stack Error: training_theme@1.0.0 build: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jeana/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jeana/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid training_theme@1.0.0
15 verbose cwd /Users/jeana/htdocs/vh-training/web/themes/custom/training_theme
16 verbose Darwin 20.6.0
17 verbose argv "/Users/jeana/.nvm/versions/node/v14.18.1/bin/node" "/Users/jeana/.nvm/versions/node/v14.18.1/bin/npm" "run" "build"
18 verbose node v14.18.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error training_theme@1.0.0 build: `gulp`
22 error Exit status 1
23 error Failed at the training_theme@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

I'm on a mac, 11.6. 

Let me know if there's any additional info I can give you to help trouble shoot this. I'm new to managing npm packages.

**Comment by systersurf** [comment]
I got exact the same problem. I'm running on a MacBook Pro m1. Monterey 12.1.
